checks:
    php: true

filter:
    excluded_paths:
        - tests/*

build:
    tests:
        override:
            - phpunit

    nodes:
        php:
            environment:
                php: 5.4

        php56:
            environment:
                php: 5.6

        php71:
            environment:
                php: 7.1