checks:
    php: true

filter:
    excluded_paths:
        - "tests/"
    dependency_paths:
        - "vendor/"

build:
    tests:
        override:

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        php:
            environment:
                php: 5.4

        php56:
            environment:
                php: 5.6

        php71:
            environment:
                php: 7.1