checks:
    php: true

filter:
    excluded_paths:
        - "tests/"
    dependency_paths:
        - "vendor/"

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=tests/php/reports/clover.xml'
                coverage:
                    file: 'tests/php/reports/clover.xml'
                    format: 'clover'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        php:
            environment:
                php: 5.4

        php56:
            environment:
                php: 5.6

        php71:
            environment:
                php: 7.1