checks:
    php: true
    javascript: true

filter:
    excluded_paths:
        - "tests/"
    dependency_paths:
        - "vendor/"
        - "node_modules/"

build:
    nodes:
        analysis:
            project_setup:
                before:
                    - make all

            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run

        php:
            environment:
                php: 5.4

        php56:
            environment:
                php: 5.6

        php71:
            environment:
                php: 7.1

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=tests/php/reports/clover.xml'
                coverage:
                    file: 'tests/php/reports/clover.xml'
                    format: 'clover'
