matrix:
  include:
    - language: php
      php: '5.4'
      before_script:
        - composer install
      cache:
        directories:
          - vendor
      script:
        - ./vendor/bin/phpunit

    - language: php
      php: '7.0'
      before_script:
        - composer install
      cache:
        directories:
          - vendor
      script:
        - ./vendor/bin/phpunit

    - language: node_js
      node_js: '10.5'
      before_script:
        - yarn install
      cache:
        directories:
          - node_modules
      script:
        - ./node_modules/.bin/mocha
