language: php

php:
  - '5.4'

before_install:
  - 'nvm install 10.5'

before_script:
  - yarn install
  - composer install

cache:
  directories:
    - node_modules
    - vendor

script:
  - ./node_modules/.bin/mocha
  - ./vendor/bin/phpunit
