# Allows use container-based infrastructure
sudo: false

# Project language
language: php
 
php:
- '5.4'
- '7.0'

matrix:
  fast_finish: true

before_script:
- composer update --no-suggest --prefer-dist --no-interaction

cache:
  directories:
  - vendor

script:
  - composer test

after_success:
  - test $TRAVIS_PHP_VERSION = "7.0" &&
    travis_retry composer coverage
